### ISSUE TITLE
Rename the subproject "emoji" to "emoticon"

### ISSUE THREAD

**Issue by seamlik** [moebiuscurve/ibus-table-others#15]
The `emoji` module is in fact for inputting [emoticons](https://en.wikipedia.org/wiki/Emoticon) rather than [emoji](https://en.wikipedia.org/wiki/Emoji). I suggest the module be renamed to `emoticon`, or at least put a hint somewhere in the project.

In modern days, an emoji means a single graphical character which is part of the Unicode standard while an emoticon means a graphical token consisting of an arrangement of multiple Unicode textual characters.

This is important considering there is already a [Debian project](https://packages.debian.org/unstable/ibus-table-emoji) representing this module and making confusion to users including me.

**Comment by mike-fabian** [comment]
Yes, maybe "emoticons" is a better name. 

When looking at the contents of

https://github.com/moebiuscurve/ibus-table-others/blob/master/tables/emoji-table.txt

it also seems that it is only useful for people who speak Chinese, all the keys one has to type to get the emoticons seem to be Chinese pinyin.

**Comment by shenlebantongying** [comment]
The original author is probably Chinese.
Problem is some distros' auto build may source that file directly from the tree.

I think it might be better if we replace it with a real emoji table (and create a new emoticon-table.txt), rather than just rename it.

**Comment by mike-fabian** [comment]
Included in https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.17

**Comment by mike-fabian** [comment]
> The original author is probably Chinese. Problem is some distros' auto build may source that file directly from the tree.
> 
> I think it might be better if we replace it with a real emoji table (and create a new emoticon-table.txt), rather than just rename it.

I just renamed it because I don’t have a real emoji table. Any contributions are welcome, of course.

But input of ̣“normal” emoji is already well supported by several other input methods like ibus-typing-booster or the core of ibus. So maybe it is not really necessary to have an emoji-table as well for ibus-table.
