### ISSUE TITLE
ubuntu bionic compatibility?

### ISSUE THREAD

**Issue by gooblegobble** [moebiuscurve/ibus-table-others#16]
NEVERMIND! It worked itself out after I uninstalled, reinstalled, logged out, and also removed fcitx from the system (which might have been causing some problems).

But: your "About" window in IBus preferences still lists the ibus.googlecode.com URL, and the copyright is very old (2009-2012).

**Comment by mike-fabian** [comment]
I cannot see the ibus.goooglecode.com URL in the about window:

![Screenshot](https://user-images.githubusercontent.com/2330175/60794529-40f64f00-a16a-11e9-8151-88c99d7c1c93.png)

I probably should update the copyright years, I did lots of development since then.

**Comment by gooblegobble** [comment]
That's not the version in Debian--I'm seeing ibus-table 1.9.14-3. I didn't build from source though.

**Comment by McSinyx** [comment]
Buster was released on July 6. Did you upgrade, it's awesome (I'm a testing user so you can trust me on this one, I'd been using it for 2 years)?

**Comment by mike-fabian** [comment]
OK, closing  this issue.
