### ISSUE TITLE
Integrate traditional Mongolian (mongol bichig) in ibus-table

### ISSUE THREAD

**Issue by mike-fabian** [moebiuscurve/ibus-table-others#23]
Originally reported here:

https://github.com/kaio/ibus-table/issues/72

**Comment by Popolon** [comment]
Just a notice that the mongol bichig is not noted in the README.

**Comment by mike-fabian** [comment]
> Just a notice that the mongol bichig is not noted in the README.

Thank you, I have added it now:

https://github.com/moebiuscurve/ibus-table-others/commit/f4727418629b14508f8f16616d0044b9e226d1d8
