### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by Socob** [moebiuscurve/ibus-table-others#25]
Apologies if I’m missing something, but there doesn’t seem to be any documentation on how to actually use the input methods provided by `ibus-table-others` (there is nothing in the `README`). Perhaps there is not much to say beyond general documentation for `ibus-table`, but I can’t find anything about that either.

**Comment by mike-fabian** [comment]
General documentation for ibus-table is here: 
http://mike-fabian.github.io/ibus-table/index.html
http://mike-fabian.github.io/ibus-table/documentation.html
http://mike-fabian.github.io/ibus-table/development.html

Although there is not much at the moment except for explaining the default key bindings and how to contribute.

But lots of the behaviour of ibus-table depends on the specific table used. Using something like the latex table is very different from using something like a Chinese jyutping table.

Currently the only way to understand how a specific table does is to look at the source of that table:

latex: https://github.com/moebiuscurve/ibus-table-others/blob/main/tables/latex.txt

https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/cantonese/jyutping.txt

But sometimes looking at the source of the table doesn’t really explain it well enough. The latex table is so simple,  that quickly browsing the source probably tells you everything.

But other tables do more complicated stuff, for example that one can type the 6 tones in Cantonese by adding v, x, q, vv, xx, qq to the input is not so obvious by browsing the table. 

And of course it is not easy for a user to find the table source to look at at all.

Therefore, I opened an issue for myself to add a feature to add help text to tables and a feature to the setup tool of ibus-table to show such help text:

[ENHANCEMENT] ibus-table should have a way to display help for tables: https://github.com/mike-fabian/ibus-table/issues/117

So far I had no time to work on this though.

**Comment by Socob** [comment]
I see – thanks! I had found the page https://mike-fabian.github.io/ibus-table/ (it *is* on the “About” page), but must have forgotten about the “Documentation” link there, because it doesn’t have much information beyond what the names of the key bindings would tell you.

I was mostly trying to figure out if I’d somehow missed anything, so for my own purposes I’d be happy with closing this issue at this point. However, if you’d like to leave it open as something to be addressed in the future, that’s fine too.

**Comment by mike-fabian** [comment]
We can close this one, I will eventually add a feature that each table can have table specific documentation and make it possible to display that easily in the setup tool for that table. But I keep track of this in 

[ENHANCEMENT] ibus-table should have a way to display help for tables: https://github.com/mike-fabian/ibus-table/issues/117
