### ISSUE TITLE
Missing "short R" from the Old Hungarian table 

### ISSUE THREAD

**Issue by rovasiras** [moebiuscurve/ibus-table-others#31]
Missing small and capital "short R" from the Old Hungarian table.

**Comment by mike-fabian** [comment]
I wonder what the typing sequence for that should be ...

On the keyboard layout (xkbconfig and keyman, it is on `AltGr+r` and `AltGr+R`. But AltGr cannot be used that way in ibus-table 

This is possible in m17n-db. I will do the same changes we are doing here for the hu-old-hungarian-rovas.txt in ibus-table later also for https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/hu-rovas-post.mim There I can use AltGr. So I will do it there. But here in ibus-table we need an alternative to using AltGr.

**Comment by mike-fabian** [comment]
Included in Release 1.3.16: https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.16
