### ISSUE TITLE
Missing Old Hungarian numbers.

### ISSUE THREAD

**Issue by rovasiras** [moebiuscurve/ibus-table-others#32]
Missing Old Hungarian numbers: one, five, ten, fifty, hundred and thousend.

**Comment by mike-fabian** [comment]
https://en.wikipedia.org/wiki/Old_Hungarian_script also lists a Old Hungarian 500, but that doesn’t seem to exist in Unicode.

Is that just an error in the Wikipedia page or is there maybe a ligature for 500?

**Comment by rovasiras** [comment]
> https://en.wikipedia.org/wiki/Old_Hungarian_script also lists a Old Hungarian 500, but that doesn’t seem to exist in Unicode.
> 
> Is that just an error in the Wikipedia page or is there maybe a ligature for 500?

No, it is not an error or ligature. This is deliberate misrepresentation, overriding the standard. Look at for example the form of "Old Hungarian close e".

**Comment by mike-fabian** [comment]
> > https://en.wikipedia.org/wiki/Old_Hungarian_script also lists a Old Hungarian 500, but that doesn’t seem to exist in Unicode.
> > Is that just an error in the Wikipedia page or is there maybe a ligature for 500?
> 
> No, it is not an error or ligature. This is deliberate misrepresentation, overriding the standard. 

If no such thing exists, like an Old Hungarian 500, then I think somebody should fix the Wikipedia page.

**Comment by mike-fabian** [comment]
> This is deliberate misrepresentation, overriding the standard. Look at for example the form of "Old Hungarian close e".

The Wikipedia pages


https://en.wikipedia.org/wiki/Old_Hungarian_script

https://en.wikipedia.org/wiki/Old_Hungarian_(Unicode_block)

do not mention the

U+10CCA OLD HUNGARIAN SMALL LETTER CLOSE E
U+10C8A OLD HUNGARIAN CAPITAL LETTER CLOSE E

they display the code chart not using pictures but using the characters themselves. So how they display depends on which font is used.

When NotoSansOldHungarian-Regular.ttf (from Google) is used, it looks like:

![Screenshot-NotoSansOldHungarian-Regular ttf](https://github.com/moebiuscurve/ibus-table-others/assets/2330175/99c1147a-a945-487f-bdfb-513214511bc3)

When OldHungarian.ttf is used it looks like:

![Screenshot-OldHungarian ttf](https://github.com/moebiuscurve/ibus-table-others/assets/2330175/96d2bf24-4c8e-49f8-8e6b-15872dbdfe53)

**Comment by rovasiras** [comment]
> So as far as the `close e` is concerned, the font OldHungarian.ttf probably needs to be fixed.

Yes, but the developer won't correcting. I've already sent him an email because a member of Unicode asked me to. The developer simply won't do it.

**Comment by mike-fabian** [comment]
There is an issue in github about the wrong `close e`: https://github.com/OldHungarian/old-hungarian-font/issues/6

**Comment by mike-fabian** [comment]
How do you like the way I did the numbers?
