### ISSUE TITLE
Old Hungarian section has no standalone ZWJ

### ISSUE THREAD

**Issue by rovasiras** [moebiuscurve/ibus-table-others#35]
In historical Old Hungarian texts exist ligatures. This requires a ZWJ key. True, you need a special font for this. András Tisza's "Nyilas" font uses syllabic (consonant + vowel) and double consonant ligatures.
 Misi Nyilas is the hero of a novel.

**Comment by mike-fabian** [comment]
Thank you, already working on this ...

**Comment by mike-fabian** [comment]
Included in Release 1.3.16: https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.16
