### ISSUE TITLE
Purpose of m4/as-version.m4?

### ISSUE THREAD

**Issue by hosiet** [moebiuscurve/ibus-table-others#36]
Debian ibus-table-others packager here. When reviewing the source code, I found `m4/as-version.m4` pretty strange. It has no license information attached and _seems_ not used anywhere. It is mentioned in `m4/Makefile.am` as `EXTRA_DIST`, which is also useless. Looking back into git commit history also gives no clear hint.

If the file is not used anywhere, can we delete it in the upstream repository? This will help with Debian's packaging for ibus-table-others since the file has unclear license status and tend to be purged during packaging.

**Comment by mike-fabian** [comment]
Included in https://github.com/moebiuscurve/ibus-table-others/releases/tag/1.3.17

**Comment by mike-fabian** [comment]
I had to keep `m4/Makefile.am`, I just removed `as-version.m4` from `EXTRA_DIST`. Now `m4/Makefile.am` does nothing at all but when I delete it and remove the line `m4/Makefile` from `configure.ac`:

```
# OUTPUT files
AC_CONFIG_FILES(Makefile
icons/Makefile
tables/Makefile
m4/Makefile
emoticon-src/Makefile
ibus-table-others.spec
)
```

then the build fails. So I kept that practically empty `m4/Makefile.am` for the moment.

Do you know whether it can be removed? Should it be removed? If yes, do you know how?

**Comment by hosiet** [comment]
The following patch should work. Basic idea:

* The `m4` directory must exist in source code before running `autoreconf` in order to cope with `AC_CONFIG_MACRO_DIR([m4])` macro in `configure.ac`. I am using am empty `m4/.placeholder` file to keep the directory from being purged by git automatically.
* Mentioning of `m4` subdir should be purged from `Makefile.am`.
* Mentioning of `m4/Makefile` should be purged from `configure.ac`.

-------------

```diff
diff --git a/Makefile.am b/Makefile.am
index 8f445c8..85e9083 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -20,7 +20,6 @@
 
 SUBDIRS = \
 	icons \
-	m4 \
 	tables \
 	emoticon-src \
 	$(NULL)
diff --git a/configure.ac b/configure.ac
index 4ccebfc..8e7da67 100644
--- a/configure.ac
+++ b/configure.ac
@@ -173,7 +173,6 @@ AM_CONDITIONAL([IBUS_TABLE_BUILD_MONGOLBICHIG],[test x"$enable_mongolbichig" !=
 AC_CONFIG_FILES(Makefile
 icons/Makefile
 tables/Makefile
-m4/Makefile
 emoticon-src/Makefile
 ibus-table-others.spec
 )
diff --git a/m4/.placeholder b/m4/.placeholder
new file mode 100644
index 0000000..e69de29
diff --git a/m4/Makefile.am b/m4/Makefile.am
deleted file mode 100644
index ce42b22..0000000
--- a/m4/Makefile.am
+++ /dev/null
@@ -1,22 +0,0 @@
-# vim:set ts=4
-#
-# ibus-tables-cyrillic - The Cyrillic tables for IBus-Table
-#
-# Copyright (c) 2009-2010 Caius 'kaio' Chance <me at kaio.me>
-#
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 3, or (at your option)
-# any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program; if not, write to the Free Software
-# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-
-EXTRA_DIST = \
-    $(NULL)
```

**Comment by mike-fabian** [comment]
Thank you very much! On my system, it even seems to work when the `m4` subdir is not there ...
Even when I use this:

```
$ cat autogen.sh 
#!/bin/sh
set -e
set -x

autoreconf --verbose --install --force
./configure --enable-maintainer-mode $*
```

**Comment by mike-fabian** [comment]
I see a warning:

```
$ ./autogen.sh --prefix=/usr
+ autoreconf --verbose --install --force
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
[...]
```
and no the `m4` subdir is not created and no files are copied there, but apart from that everything seems to work normally.

`make && make dist` still seems to work fine.
